language: python

matrix:
    include:
        - os: linux
          python: 2.7

        - os: linux
          python: 3.6

install:
    - pip install --upgrade pip
    - pip install --upgrade pytest-cov pytest
    - pip install -e .

# its not worth doing flake8 due to all the defs (which are many, many lines of src)

script:
    - py.test ./vstruct/tests/testbasic.py -v --cov=vstruct
    - py.test ./vstruct/tests/tests_vstruct.py -v --cov=vstruct